### ISSUE TITLE
update in free_r_tip 20 (SQL from R) required. 

### ISSUE THREAD

**Issue by fschier** [business-science/free_r_tips#1]
dplyr::across does not take a vector of c(mean, median) as a value to the .fns argument. Instead a list list(mean, median) is required.
Found this by coincidence, so other skripts might need some adaption as well.

Greetings
Felix

**Comment by WebscienceXYZ** [comment]
Thank you

**Comment by mdancho84** [comment]
Thanks. I've updated this in the lesson.
