### ISSUE TITLE
028_esquisse_ggplot/shiny_app.R

### ISSUE THREAD

**Issue by priyankagagneja** [business-science/free_r_tips#4]
mpg dataset does not exist.
You probably intended to do data("mtcars"). Similarly down below in the ui & server section.

**Comment by mdancho84** [comment]
The mpg data set comes with ggplot2.

**Comment by priyankagagneja** [comment]
ok gotcha, looks like the code needs the call to ggplot2 then(`library(ggplot1`)). either one works fine.

**Comment by mdancho84** [comment]
The code should work as-is. Tidyverse loads ggplot2, which contains the mpg dataset.
![image](https://user-images.githubusercontent.com/13734662/122752038-78c70600-d25e-11eb-87a2-062a81078b35.png)
